services:
  web:
    image: nginx:latest
    ports:
      - "4567:80"
    volumes:
      - .:/usr/share/nginx/html/
    command: /bin/sh -c "cp /usr/share/nginx/html/index.html /usr/share/nginx/html/index.html.bak && rm -f /usr/share/nginx/html/index.html && cp /usr/share/nginx/html/index.html.bak /usr/share/nginx/html/index.html && nginx -g 'daemon off;'"